### ISSUE TITLE
[BUG] Call to a member function link() on a non-object

### ISSUE THREAD

**Issue by zomars** [bolt/PasswordProtect#10]
I've added the`{{ passwordprotect() }}` twig tag to my `index.twig` file and I'm getting this error:
![captura de pantalla 2016-08-16 a las 4 15 25 p m](https://cloud.githubusercontent.com/assets/3504472/17717718/d4f37a72-63cc-11e6-8602-86b5e9fbfc0d.png)

**Comment by ruettenm** [comment]
you have to configure `redirect` to an existing page.

**Comment by zomars** [comment]
Clearing things up, I've made a redirect but I didn't knew it has to be like `page/1` I've tried to use a `page/slug`and didn't work. It is working now.
