### ISSUE TITLE
[BUG] Only root can see the set password backend page

### ISSUE THREAD

**Issue by graham73may** [bolt/PasswordProtect#14]
When logged in as root:
![image](https://cloud.githubusercontent.com/assets/6642498/23455161/933dc6f2-fe66-11e6-8100-66017bc5d7b2.png)

When logged in as admin (the role of my client):
![image](https://cloud.githubusercontent.com/assets/6642498/23455181/9fbd2954-fe66-11e6-9747-e0145dd6db93.png)

I've tried to set a `permission: ` in the config, however this did not work. I also tried to set a permission in the extensions `getDefaultConfig()` however this did not work either. 

Not quite sure what is stopping the menu entries from being added.

**Comment by bobdenotter** [comment]
Fixed in #17
