### ISSUE TITLE
Twigcode is not working

### ISSUE THREAD

**Issue by djoeybodenstaff** [bolt/PasswordProtect#2]
Hello,
On a website of a client of mine I need some pages to be password protected.
To do this I've installed this extension, and I've activated it. I can configure it in the extensions section but on the front end it is not working.
You need to add a simple code to your body or your template if you want to get that page password protected. But, on the front-end the code is not picked up and stands there like a weird word.
How can I fix this?

**Comment by bobdenotter** [comment]
Hi, can I get a screenshot of what you're seeing?

**Comment by djoeybodenstaff** [comment]
Okay:

**Comment by bobdenotter** [comment]
I don't think that worked how you expected it to work. ;-)

**Comment by bobdenotter** [comment]
Have you added `allowtwig: true` to the fields in the contenttypes where you want to add this?

**Comment by djoeybodenstaff** [comment]
Ahaa, no..
But after I've added that property I'm getting this error:
The function "passwordprotect" does not exist in "{{ passwordprotect() }}" at line 1
